language: rust
rust:
  - stable
  - beta
  - nightly
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os: linux
before_install:
  - sudo apt-get update
  - sudo apt-get -y install gcc-arm-none-eabi
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  
